### ISSUE TITLE
@ExternalDocumentation within @Schema annotation doesn't get added to the generated openapi specs

### ISSUE THREAD

**Issue by popprem** [taymyr/lagom-openapi#18]
I've noticed that @ExternalDocumentation within @Schema annotation doesn't get added to the generated openapi specs, example:

```
@ApiResponse(
            responseCode = "200",
            description = "Some response",
            content =
                @Content(
                    mediaType = "application/json",
                    schema =
                        @Schema(
                            implementation = Some.class,
                            externalDocs =
                                @ExternalDocumentation(
                                    url ="some url"))))
```

Note that it works within @OpenAPIDefinition annotation.

```
@OpenAPIDefinition(
    info =
        @Info(// some info),
    servers = {// some servers},
    externalDocs =
        @ExternalDocumentation(
            description = "Documentation with examples",
            url = "some url"))
```
Is this an issue with `lagom-openapi` module?

**Comment by ihostage** [comment]
@popprem If you use `implementation = Some.class`, you need to use `externalDocs` property on `@Schema` annotation for `Some` class. For example, see test class `User` with `example` property for `@Schema` annotation. https://github.com/taymyr/lagom-openapi/blob/3387c699e304be744e2be554ae02835480349f50/core/src/test/java/org/taymyr/lagom/internal/openapi/cases/User.java#L5-L6
