### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by ihostage** [taymyr/lagom-openapi#21]
Depends on: #22

**Comment by bauwenssimon** [comment]
Any update on this feature?

**Comment by ihostage** [comment]
@bauwenssimon Yes, of course. 😄Sorry for the long reaction.

**Comment by ihostage** [comment]
@bauwenssimon You can try a `1.1.0-SNAPSHOT` version from [Sonatype Snapshots](https://oss.sonatype.org/content/repositories/snapshots/) repository.
