### ISSUE TITLE
Add support to deprecate endpoints

### ISSUE THREAD

**Issue by nikhilaroratgo** [taymyr/lagom-openapi#40]
@Operation supports the field `deprecated = true`. Adding this field doesn't generate the yml with deprecated field.
For example
 ```
@Operation(
        deprecated = true,
        operationId = "testOperationId",
        description = "This is a test description",
        summary = "(DEPRECATED)",
        parameters = { ..
      )
```

It would be nice to have this feature
Meanwhile, I used `summary` field for this purpose

**Comment by stankevichevg** [comment]
@nikhilaroratgo Thank you for the issue reporting!
The problem is solved and the feature will be available in the next release.

**Comment by ihostage** [comment]
@stankevichevg Thank a lot for the quick fix! :+1:
