### ISSUE TITLE
OpenAPI spec for aggregate?

### ISSUE THREAD

**Issue by normenmueller** [taymyr/lagom-openapi#42]
Is there an option to download the OpenAPI spec for the aggregate of all services? For example, given the following aggregate

```
lazy val `myprj` = (project in file("."))
    .settings(
      name := "myprj",
      scalaVersion := "2.13.3")
    .aggregate(
      `svcA-api`, `svcA-impl`,
      `svcB-api`, `svcB-impl`,
      `svcC-api`, `svcC-impl`)
```

the OpenAPI spec of this aggregate could be available via

```
curl "http://localhost:9000/_myprj/openapi?format=yaml"
```

For sure on a dedicated place for `@OpenAPIDefinition` etc. must be decided. Maybe a static file at the project root.

**Comment by ihostage** [comment]
It's possible only using a static file in one of your `srvX-impl`. 
Or, maybe, by using 3rd party tools for aggregate OpenAPI specs from all services.

**Comment by normenmueller** [comment]
@ihostage Thx

> Or, maybe, by using 3rd party tools for aggregate OpenAPI specs from all services.

That's what I'm actually doing... ;-)
